import type { ConvenioCashFlow, ConvenioPaymentMethod } from '@/modules/convenios/domain/entities/Convenio';

export type CreateConvenioInput = {
  id: string;
  convenioCode: string;
  name: string;
  cpfCnpj?: string;
  stateRegistration?: string;
  tradeName?: string;
  personType?: 'FISICA' | 'JURIDICA';
  birthDate?: string;
  rg?: string;
  municipalRegistration?: string;
  gender?: string;
  entryOrigin?: string;
  deliveryServiceFee?: string;
  customerConvenio?: string;
  managerName?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  cep?: string;
  address?: string;
  number?: string;
  neighborhood?: string;
  state?: string;
  city?: string;
  complement?: string;
  stateTaxpayerType?: string;
  activityType?: string;
  freightMode?: string;
  creditLimit?: string;
  debitLimit?: string;
  fiadoLimit?: string;
  creditCardLimit?: string;
  discountPercent?: string;
  commissionPercent?: string;
  visitDay?: string;
  visitRegion?: string;
  printLocation?: string;
  crt?: string;
  cnae?: string;
  priceTable?: string;
  cei?: string;
  constructionRegistration?: string;
  category?: string;
  suframa?: string;
  billingCondition?: string;
  carrierName?: string;
  paymentMethod: ConvenioPaymentMethod;
  cashFlow: ConvenioCashFlow;
  bankName: string;
  accountName: string;
  active: boolean;
  notes: string;
};
