CREATE TABLE usuarios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  cargo ENUM('ADMIN', 'CAIXA', 'COMANDA') NOT NULL,
  senha_hash VARCHAR(255) NOT NULL
);

CREATE TABLE produtos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  preco_venda DECIMAL(10,2) NOT NULL,
  custo DECIMAL(10,2) NOT NULL,
  estoque INT NOT NULL DEFAULT 0
);

CREATE TABLE comandas (
  id INT PRIMARY KEY AUTO_INCREMENT,
  status ENUM('ABERTA', 'FECHADA') NOT NULL DEFAULT 'ABERTA',
  total DECIMAL(10,2) NOT NULL DEFAULT 0.00
);
