export type Product = {
  id: string;
  productCode: string;
  name: string;
  category: string;
  ncm?: string;
  cfop?: string;
  cstIcms?: string;
  taxSituationCode?: string;
  aliqIcms?: string;
  cstPis?: string;
  aliqPis?: string;
  cstCofins?: string;
  aliqCofins?: string;
  fiscalType?: string;
  costValue?: number;
  marginProfit?: number;
  price: number;
  byWeight: boolean;
  stock: number;
  version: number;
  createdAt: Date;
  updatedAt: Date;
  lastSyncedAt?: Date;
};
