export type CreateProductInput = {
  id: string;
  productCode: string;
  barcode?: string;
  imageUrl?: string;
  name: string;
  description?: string;
  category: string;
  isUnavailable?: boolean;
  isHidden?: boolean;
  ncm: string;
  cfop: string;
  cstIcms: string;
  taxSituationCode: string;
  aliqIcms: string;
  cstPis: string;
  aliqPis: string;
  cstCofins: string;
  aliqCofins: string;
  fiscalType: string;
  costValue: number;
  marginProfit: number;
  price: number;
  byWeight: boolean;
  stock: number;
};
